### ISSUE TITLE
Не работает...

### ISSUE THREAD

**Issue by AliAlievALive** [AliAlievALive/web-app1#1]

**Comment by coursar** [comment]
Вы повесили не тот бейджик от тревиса. Повесьте правильный и будем разбираться, что не работает конкретно.

**Comment by coursar** [comment]
В Heroku зайдите в ваше приложение и добавьте меня в коллабораторы:

<img width="844" alt="Снимок экрана 2019-11-13 в 15 18 07" src="https://user-images.githubusercontent.com/3601892/68763188-e5146900-0628-11ea-94f3-772af7d43b8a.png">

**Comment by AliAlievALive** [comment]
Бейдж исправил, в коллабораторы добавил

**Comment by coursar** [comment]
Сделайте `git pull`
